
[database]
    name = "PinkCloud"
    connectionStr = "mongodb://localhost:27017"

[discordClient]
    id = ""
    secret = ""

[security]
    logRounds = 12

[cookieSecrets]
    sign = "g2fkmK74tiOkV9KKgCKzZw=="
    encryption = "uExoI+3ciEX8qiuIXuTTug=="