
[cookieSecrets]
    sign = "52783606936b9c35d1223be30c0e19b5"
    encryption = "7b9279d53151719a2300dd36fb08c191"

[database]
    name = "PCSSharedAPI"
    connectionStr = "mongodb://admin:hGZor59gz8RU6UzuJDb4YprF@100.105.201.65:40006/"

[security]
    logRounds = 12

[email]
    address = "no-reply@pinkcloud.studio"
    password = "4jcU3MEYOVZ3h0g2"

[discordClient]
    id = ""
    secret = ""