
[cookieSecrets]
    sign = ""
    encryption = ""

[database]
    name = "PCSSharedAPI"
    connectionStr = ""

[security]
    logRounds = 12

[email]
    address = "no-reply@pinkcloud.studio"
    password = ""

[discordClient]
    id = ""
    secret = ""