
[cookieSecrets]
    sign = ""
    encryption = ""

[database]
    name = "SharedAPI"
    connectionStr = "mongodb://localhost:27017"

[security]
    logRounds = 12

[email]
    address = "no-reply@pinkcloud.studio"
    password = ""

[discordClient]
    id = ""
    secret = ""