
[database]
    name = "PinkCloud"
    connectionStr = "mongodb://localhost:27017"

[cookieSecrets]
    sign = ""
    encryption = ""

[discordClient]
    id = ""
    secret = ""

[security]
    logRounds = 12